### ISSUE TITLE
leksah-server does not shut down properly sometimes on Ubuntu

### ISSUE THREAD

**Issue by JPMoresmau** [leksah/leksah#125]
I have Ubuntu 15.04, and the dev version of leksah and leksah server. In the preferences, I have the option to shut down the leksah server when there's no more connections to it. If I launch leksah-server myself, there is no issue. If leksah-server is started from leksah itself, sometimes, but not always, the server is not shut down when the GUI is. I still see leksah-server in the process list.
I think that what happens, looking at the logs when the shut down wasn't complete, is that leksah shuts down, the leksah-server process receives a SIGHUP signal, and that causes issues. I saw in the log something like:
- last connection, existing
- leksah-server: signal : 1

So instead of ending with ExitSuccess, the signal wreaks havoc. 

This would not be a huge issue if I didn't have the case this morning where leksah would connect to such a zombie instance and get no results what so ever from it, so the Modules view was empty, etc.

Maybe the UI could have an explicit way to shut down the server cleanly, or maybe we can handle SIGHUP better?

**Comment by hamishmack** [comment]
There was a time when we had a really bad way of interrupting `cabal build` and it would bring down leksah-server as well.  I think I did something to prevent that from happening (IIRC we got leksah-server to ignore the SIGINT).  We fixed the problem by improving the process module and now the SIGINT is sent only to the process running `cabal build`.

I thought I changed leksah-server back so it did not ignore SIGINT.  But even so it still sometimes does and I find myself having to killall -9 leksah-server because killall leksah-server does not work.

Perhaps I missed something in leksah-server that is still disabling signal handling or perhaps there is something about the way the process is started.
