### ISSUE TITLE
Event buffer overflowed

### ISSUE THREAD

**Issue by ka3a4ok** [leksah/leksah#141]
Multiple "event buffer overflowed, event dropped" in server console. IDE works freezely.

**Comment by hamishmack** [comment]
Please try [0.15.1.2](https://github.com/leksah/leksah/wiki/Leksah-0.15.1.2), though I am not sure it will help.

How often does this happen?  What version of Windows?  What sort of machine? Does it seem to happen when one of the WebKitGTK+ panes first starts?  Does turning of background builds make it go away?

If it is happening only since 0.15.1.0 then it might be related to the switch to the threaded RTS.  The main loop used by Leksah is different in the threaded RTS and it may be broken.

**Comment by hamishmack** [comment]
This was probably the main loop issue (fixed in 0.15.1.3).  Pleas let us know if it is still happening.
