### ISSUE TITLE
UI is not completely dark, only code editor how to fix it?

### ISSUE THREAD

**Issue by nodermann** [leksah/leksah#261]
leksah 0.15.0.0
Ubuntu 14.04
ghc 7.8.4
cabal 1.22
Screenshot: http://prnt.sc/aa605n

I need like on this screenshot http://leksah.org/images/Bildschirmfoto-leksah-13-linux.png

any ideas?

**Comment by jaccokrijnen** [comment]
Have you selected View -> Dark Interface in the menu?

**Comment by nodermann** [comment]
yes, and I tried Preferences -> UI http://prnt.sc/aa6ez3

**Comment by jaccokrijnen** [comment]
I think that the problem is that Ubuntu's default "ambiance" gtk theme does not have support for a dark variant. You can change your system gtk themes using gnome-tweak-tool (install with apt-get). For example Adwaita supports dark, I use arc theme (https://github.com/horst3180/arc-theme), so Leksah looks like this (http://imgur.com/tCWENaC)

**Comment by nodermann** [comment]
Yes, it works with Adwaita, thank you :)
