### ISSUE TITLE
Leksah on hackage does not build (easily)

### ISSUE THREAD

**Issue by jaccokrijnen** [leksah/leksah#300]
I've spent quite a while trying to build leksah 0.15.2. from Hackage, which used to work. This is what I found

* Building from Hackage fails with the new version of `gtk3`: [log](https://gist.github.com/jaccokrijnen/bb6b70f3c34f36d78ed3ead5b0cc6e79)
* When specifying an older version of `gtk3`, `Cabal-1.24` gets in the way (installed by `gtk2hs-buildtools`), because leksah requires `Cabal<1.23`: [log](https://gist.github.com/jaccokrijnen/1eaf45d5b373eaefd3b486adb0513251)
*  When specifying an older version of `gtk3` as well as `Cabal-1.22`, we have complaining gtk2hs packages, because they now have a `setup-depends` on `gtk2hs-buildtools` which introduces a dependency on `Cabal-1.24` again.
* When specifying older versions of the gtk2hs packages as well as lens, I got compile errors in Cairo's setup, since Dist.Simple.GHC changed the signature of `getInstalledPackages` in 1.24 (used by my `cabal-install 1.24`): [log](https://gist.github.com/jaccokrijnen/b9467c285af2538b0f915b5479b9d7e9).
* Downgrading to `cabal-install` 1.22, I found a working install plan!

```
$ cabal --version
cabal-install version 1.22.8.0
using version 1.22.6.0 of the Cabal library 

$ cabal sandbox init

# make sure ~/.cabal/bin is in PATH
$ cabal --ignore-sandbox install gtk2hs-buildtools-0.13.0.5


$ cabal install leksah --constraint="gtk3==0.14.2" --constraint="cairo==0.13.1.0" --constraint="glib==0.13.2.1" --constraint="gio==0.13.1.0" --constraint="pango==0.13.1.0" --constraint="gtksourceview3==0.13.2.0" --constraint="webkitgtk3==0.14.1.0" --constraint="webkitgtk3-javascriptcore==0.13.1.2" --constraint="webkit-javascriptcore==0.13.1.2" --constraint="lens==4.13"

...

Installed leksah-0.15.2.0
```

Some thoughts:

* I think that we should somehow freeze the dependencies when releasing a new leksah version on Hackage (so it's easier to reproduce sandbox builds and avoid these situations). But maybe I'm wrong, are there any good reasons to specify version bounds on a Hackage release?
* We should fix leksah-0.15.2 on Hackage (maybe we shouldn't release 0.16 yet, there are some gtk related bugs such as #299 )
   * Either we make it work with cabal 1.24
   * Or we only support `cabal-install 1.22` and tighten the upperbounds according to these constraints I found

It was an interesting safari through cabal and hackage, and I learned some things :)

**Comment by hamishmack** [comment]
Argh it's https://github.com/gtk2hs/gtk2hs/issues/174 again.  I screwed up the `#ifdef`s for GTK.  All the more reason to switch to `haskell-gi` ASAP.

I have pushed [this fix](https://github.com/gtk2hs/gtk2hs/commit/0b53913e456ad56147555f0de8d22147d2f4815e).

Can you try Cabal 1.24 and Hackage again, but build `gtk3` from github?

**Comment by hamishmack** [comment]
Fix is in Hackage now `gtk3-0.14.5`

**Comment by hamishmack** [comment]
> I think that we should somehow freeze the dependencies when releasing a new leksah version on Hackage (so it's easier to reproduce sandbox builds and avoid these situations). But maybe I'm wrong, are there any good reasons to specify version bounds on a Hackage release?

I think we will have to do this with the OS package manager.  Stack or cabal freeze will work for projects with only a few external dependencies, but I don't think it will help us because Gtk is such a big and important external dependency (this is why the build broke in this case, I tested with a different version of Gtk).  If we can release RPM and DEB along with the Windows and OS X installers I think we will have most people covered.  Remember all the Windows and OS X users are already immune to these build issues as they can always grab the installer.

**Comment by jaccokrijnen** [comment]
Thanks for the fix! It installs fine now.

I agree, prepackaged binaries for Linux would be a good solution. I don't really understand though, why is pinning the version of an external dependency like gtk3 in a hackage release a bad idea? Then the build wouldn't have been broken in the first place, right?

**Comment by hamishmack** [comment]
The Hackage build of Leksah first broke when people started using Cabal 1.24, because the gtk3 package in Hackage would not build with Cabal 1.24.  To fix that I release a new gtk3 package, unfortunately one with some other build issues.

Going forward we now have a `custom-setup` section in gtk3 that requests Cabal <1.25, so hopefully when people upgrade to Cabal 1.26 we can take our time because gtk3 should keep working.
