### ISSUE TITLE
Problem installing

### ISSUE THREAD

**Issue by FlavouredGeorge** [leksah/leksah#328]
I am trying to install Leksah, I followed the setps on github but got:

trying: leksah-0.15.2.0 (user goal)
next goal: base (dependency of leksah-0.15.2.0)
rejecting: base-4.9.0.0/installed-4.9... (conflict: leksah => base>=4.0.0.0 &&
<4.9)
rejecting: base-4.9.0.0, base-4.8.2.0, base-4.8.1.0, base-4.8.0.0,
base-4.7.0.2, base-4.7.0.1, base-4.7.0.0, base-4.6.0.1, base-4.6.0.0,
base-4.5.1.0, base-4.5.0.0, base-4.4.1.0, base-4.4.0.0, base-4.3.1.0,
base-4.3.0.0, base-4.2.0.2, base-4.2.0.1, base-4.2.0.0, base-4.1.0.0,
base-4.0.0.0, base-3.0.3.2, base-3.0.3.1 (constraint from non-upgradeable
package requires installed instance)
Backjump limit reached (currently 2000, change with --max-backjumps or try to
run with --reorder-goals).

I'm running Arch linux 4.6.4-1, ghc 8.0.1, cabal-install version 1.24.0.0 (compiled using version 1.24.0.0 of the Cabal library, if that is of any relevance). The other libraries are whatever cabal installed and the one which github specified to install via package manager are:

gtksourceview3 3.20.4-1
webkitgtk 2.4.11-1

The "latest&default" version in the repositories of Arch, as far as I know.

Any help would be appreciated.

**Comment by A-Manning** [comment]
Have you tried the 0.16 build here https://ci.appveyor.com/project/hamishmack/leksah/build/1.0.122/artifacts ?

**Comment by hamishmack** [comment]
If you want to build leksah with GHC 8.0 you will need to build 0.16 from github.  I have just updated the instructions a bit ([leksah build instructions](https://github.com/leksah/leksah/blob/master/Readme.md#building-from-source)).

It might be a while before we can put 0.16 in hackage.  The problem is that with out the flags specified in the github version [here](https://github.com/leksah/leksah/blob/master/cabal.project#L1) for haskell-gi, leksah would take a very long time to build.  We need to work out a good way to make sure people don't miss these out when building from hackage.

**Comment by jaccokrijnen** [comment]
We have verified that the build from github instructions work on Arch
